spring.application.name=credit-card-service

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.url=jdbc:postgresql://localhost:5432/creditscore_db
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

zbank.kafka.consumer.rating-result.group-id=credit-card-rating-group

# Ensure these are in your CreditCardService application.properties
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# FIX: This must be JsonSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Add headers so the consumer knows how to read the JSON back into a class
spring.kafka.producer.properties.spring.json.add.type.headers=true